application: brightontimes
version: 1
runtime: python27
api_version: 1
threadsafe: true

# sets cache-control and experation 
#but does not re set any caches so 
#10-min expiration time on redeployment

# default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on


handlers:
- url: /favicon.ico
  static_files: b_times/static/img/favicon.ico
  upload: b_times/static/img/favicon.ico

- url: /robots.txt
  static_files: b_times/static/robots.txt
  upload: b_times/static/robots.txt

- url: /gae_mini_profiler/static
  static_dir: lib/gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: lib.gae_mini_profiler.main.b_times

# set url to find static folder
- url: /static
  static_dir: b_times/static

# set url to images folder
- url: /(.*\.(gif|png|jpg))$
  static_files: b_times/static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /admin/.*
  script: admin.app
  login: admin

- url: .*
  script: run.b_times.app